#!/usr/bin/env python3
"""
scene_gen.py - Generate a new scene from templates

This script uses templates generated by template_gen.py to create new scenes.
It handles multiple shaders with custom names and copies all associated resources.

Usage: 
    python scene_gen.py <scene_name> [options]
    python scene_gen.py "My New Scene" -e my_new_scene -t refactored_per_frag
"""

import os
import sys
import argparse
import shutil
import re
from pathlib import Path
from datetime import datetime


def load_template(template_path):
    """Load a template file and return its contents."""
    try:
        with open(template_path, 'r') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: Template file not found: {template_path}")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading template {template_path}: {e}")
        sys.exit(1)


def find_shader_placeholders(cpp_template):
    """
    Find all shader placeholder variables in the C++ template.
    Returns a list of shader indices found (e.g., [0, 1, 2, 3])
    """
    pattern = r'\{shader_(\d+)\}'
    matches = re.findall(pattern, cpp_template)
    return sorted(set(int(idx) for idx in matches))


def find_template_files(templates_dir, base_name):
    """
    Find all template files associated with a base template name.
    Returns dict with keys: 'cpp', 'shaders', 'meshes'
    """
    templates_path = Path(templates_dir)
    cpp_template = templates_path / f"{base_name}.cpp.template"
    
    if not cpp_template.exists():
        print(f"Error: Template {cpp_template} not found!")
        sys.exit(1)
    
    # Find shader templates
    shader_templates = sorted(templates_path.glob("*.vert.template")) + \
                      sorted(templates_path.glob("*.frag.template")) + \
                      sorted(templates_path.glob("*.geom.template")) + \
                      sorted(templates_path.glob("*.comp.template"))
    
    # Find mesh templates
    mesh_templates = sorted(templates_path.glob("*.glb.template")) + \
                    sorted(templates_path.glob("*.obj.template")) + \
                    sorted(templates_path.glob("*.fbx.template"))
    
    return {
        'cpp': cpp_template,
        'shaders': shader_templates,
        'meshes': mesh_templates
    }


def get_shader_extension(template_name):
    """Extract the shader extension from template name (e.g., .vert, .frag)"""
    # Remove .template extension first
    name = template_name.replace('.template', '')
    # Get the extension
    ext_parts = name.split('.')
    if len(ext_parts) >= 2:
        return '.' + ext_parts[-1]
    return ''


def prompt_shader_names(shader_count, template_files, scene_name_safe):
    """
    Interactive prompt to get shader filenames from user.
    Returns a dict mapping shader_N to (template_path, output_filename).
    """
    print(f"\nFound {shader_count} shader placeholder(s) in template.")
    print(f"Available shader templates: {len(template_files['shaders'])}")
    
    for i, shader_template in enumerate(template_files['shaders']):
        print(f"  [{i}] {shader_template.name.replace('.template', '')}")
    
    shader_mapping = {}
    
    for i in range(shader_count):
        while True:
            print(f"\nShader {i} (shader_{i}):")
            template_idx = input(f"  Select template [0-{len(template_files['shaders'])-1}]: ").strip()
            
            # Must select a template
            if not template_idx.isdigit():
                print(f"  Please enter a valid template index")
                continue
                
            idx = int(template_idx)
            if not (0 <= idx < len(template_files['shaders'])):
                print(f"  Invalid index. Please enter 0-{len(template_files['shaders'])-1}")
                continue
            
            template_path = template_files['shaders'][idx]
            template_base = template_path.name.replace('.template', '')
            
            # Get the extension (e.g., .vert, .frag)
            shader_ext = get_shader_extension(template_path.name)
            
            # Suggest a default name
            default_name = f"{scene_name_safe}_{i}{shader_ext}"
            custom_name = input(f"  Enter output filename (default: {default_name}): ").strip()
            
            if not custom_name:
                custom_name = default_name
            
            # Ensure it has the correct extension
            if not custom_name.endswith(shader_ext):
                custom_name += shader_ext
            
            shader_mapping[i] = (template_path, custom_name)
            print(f"  ✓ Template: {template_base} -> Output: {custom_name}")
            break
    
    return shader_mapping


def substitute_variables(template, variables):
    """Replace {variable_name} placeholders in template with actual values."""
    result = template
    for key, value in variables.items():
        result = result.replace(f"{{{key}}}", value)
    return result


def create_scene(scene_name, executable_name=None, template_name=None, templates_dir="templates", auto_mode=False):
    """
    Create a new scene from templates.
    
    Args:
        scene_name: Display name of the scene
        executable_name: Name for the executable (defaults to sanitized scene_name)
        template_name: Base name of template to use (e.g., 'refactored_per_frag')
        templates_dir: Directory containing templates
        auto_mode: If True, automatically assign shader names without prompting
    """
    if executable_name is None:
        executable_name = scene_name.lower().replace(' ', '_')
    
    # Sanitize the scene name for filenames
    scene_name_safe = scene_name.lower().replace(' ', '_')
    
    # Determine template to use
    if template_name is None:
        # Try to find a template automatically
        templates_path = Path(templates_dir)
        cpp_templates = list(templates_path.glob("*.cpp.template"))
        
        if not cpp_templates:
            print(f"Error: No .cpp.template files found in {templates_dir}")
            sys.exit(1)
        
        if len(cpp_templates) == 1:
            template_name = cpp_templates[0].name.replace('.cpp.template', '')
            print(f"Using template: {template_name}")
        else:
            print(f"Multiple templates found in {templates_dir}:")
            for i, tmpl in enumerate(cpp_templates):
                print(f"  [{i}] {tmpl.name}")
            
            choice = input(f"Select template [0-{len(cpp_templates)-1}]: ").strip()
            if choice.isdigit() and 0 <= int(choice) < len(cpp_templates):
                template_name = cpp_templates[int(choice)].name.replace('.cpp.template', '')
            else:
                print("Invalid selection")
                sys.exit(1)
    
    # Setup paths
    base_path = Path("src") / scene_name_safe
    shaders_path = base_path / "shaders"
    meshes_path = base_path / "meshes"
    
    # Create directories
    base_path.mkdir(parents=True, exist_ok=True)
    shaders_path.mkdir(parents=True, exist_ok=True)
    meshes_path.mkdir(parents=True, exist_ok=True)
    
    # Find all template files
    template_files = find_template_files(templates_dir, template_name)
    
    # Load C++ template
    cpp_template = load_template(template_files['cpp'])
    
    # Find shader placeholders
    shader_indices = find_shader_placeholders(cpp_template)
    
    # Get shader names
    if auto_mode:
        # Auto-assign shader names from available templates
        shader_mapping = {}
        for i, idx in enumerate(shader_indices):
            if i < len(template_files['shaders']):
                template_path = template_files['shaders'][i]
                shader_ext = get_shader_extension(template_path.name)
                output_name = f"{scene_name_safe}_{i}{shader_ext}"
                shader_mapping[idx] = (template_path, output_name)
            else:
                # Fallback if we somehow have more placeholders than templates
                shader_mapping[idx] = (None, f"{scene_name_safe}_{i}.vert")
        print(f"\nAuto-assigned {len(shader_mapping)} shader(s)")
    else:
        # Interactive mode
        shader_mapping = prompt_shader_names(len(shader_indices), template_files, scene_name_safe)
    
    # Build variables dictionary
    variables = {
        'scene_name': scene_name,
        'scene_name_safe': scene_name_safe,
        'executable_name': executable_name,
        'date': datetime.now().strftime('%Y-%m-%d'),
        'year': datetime.now().strftime('%Y')
    }
    
    # Add shader variables
    for idx, (template_path, output_name) in shader_mapping.items():
        variables[f'shader_{idx}'] = output_name
    
    # Process C++ template
    cpp_content = substitute_variables(cpp_template, variables)
    
    # Write C++ file
    cpp_file = base_path / f"{scene_name_safe}.cpp"
    cpp_file.write_text(cpp_content)
    print(f"\n✓ Created {cpp_file}")
    
    # Process and copy shader files based on mapping
    print(f"\n✓ Processing shader files:")
    for idx, (template_path, output_name) in shader_mapping.items():
        if template_path is None:
            print(f"  Warning: No template for shader_{idx}, skipping")
            continue
            
        # Load template content
        shader_content = load_template(template_path)
        shader_content = substitute_variables(shader_content, variables)
        
        # Write shader file with the user-specified name
        shader_output = shaders_path / output_name
        shader_output.write_text(shader_content)
        print(f"  shader_{idx}: {template_path.name.replace('.template', '')} -> {output_name}")
    
    # Copy mesh files
    if template_files['meshes']:
        print(f"\n✓ Processing mesh files:")
        for mesh_template_path in template_files['meshes']:
            # Remove .template extension
            mesh_name = mesh_template_path.name.replace('.template', '')
            mesh_dest = meshes_path / mesh_name
            
            shutil.copy2(mesh_template_path, mesh_dest)
            print(f"  {mesh_name}")
    else:
        print(f"\n⚠ No mesh templates found")
    
    # Update CMakeLists.txt
    cmake_path = Path("src") / "CMakeLists.txt"
    if cmake_path.exists():
        with open(cmake_path, 'a') as f:
            f.write(f'\nadd_scene("{scene_name}" "{executable_name}" "{scene_name_safe}.cpp")\n')
        print(f"\n✓ Added to {cmake_path}")
    else:
        print(f"\n⚠ Warning: {cmake_path} not found, skipping CMakeLists.txt update")
    
    print(f"\n{'='*60}")
    print(f"✓ Scene '{scene_name}' created successfully!")
    print(f"{'='*60}")
    print(f"  Source:     {cpp_file}")
    print(f"  Shaders:    {shaders_path}/ ({len(shader_mapping)} files)")
    print(f"  Meshes:     {meshes_path}/ ({len(template_files['meshes'])} files)")
    print(f"  Executable: {executable_name}")
    print(f"{'='*60}\n")


def main():
    parser = argparse.ArgumentParser(
        description='Create a new scene from templates',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s "My New Scene"
  %(prog)s "Physics Demo" -e physics_demo -t refactored_per_frag
  %(prog)s "Lighting Test" --auto
        """
    )
    
    parser.add_argument('name', help='Name of the scene')
    parser.add_argument('-e', '--executable', help='Executable name (defaults to sanitized scene name)')
    parser.add_argument('-t', '--template', help='Template name to use (e.g., refactored_per_frag)')
    parser.add_argument('--templates-dir', default='templates', 
                        help='Path to templates directory (default: templates)')
    parser.add_argument('--auto', action='store_true',
                        help='Automatically assign shader names without prompting')
    
    args = parser.parse_args()
    
    create_scene(
        args.name, 
        args.executable, 
        args.template,
        args.templates_dir,
        args.auto
    )


if __name__ == "__main__":
    main()